name: ArxivAutoForward

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
  
jobs:
  get_arxiv:
    runs-on: ubuntu-latest
    steps:
    -name: CrawArxiv
    run: curl https://arxiv.org/list/cs.CL/recent > ./arxiv.html
      
  send_mail:
    runs-on: ubuntu-latest
    needs: get_arxiv

    steps:
    - name: SendMail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.SENDER_MAIL_USERNAME}}
        password: ${{secrets.SENDER_MAIL_PASSWORD}}
        subject: Axiv Auto-forward 
        to: ${{secrets.RECEIVER_ADDR}}
        from: no-reply
        secure: true
        body: Arxiv from today
        html_body: file://arxiv.html
        ignore_cert: true
        convert_markdown: true
    
