name: ArxivAutoForward

on:
  schedule:
    - cron: '00 04 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Prepare environments
      run: pip install json2html
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Query
      run: python query.py
      env:
          DATE: ${{ steps.date.outputs.date }}
    - name: SendMail
      run: python send_mail.py
      env:
          USERNAME: ${{ secrets.SENDER_MAIL_USERNAME }}
          PASSWORD: ${{ secrets.SENDER_MAIL_PASSWORD }}
          RECEIVERS: ${{ secrets.RECEIVER_ADDR }}
          DATE: ${{env.REPORT_DATE}}

    
