name: ArxivAutoForward

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: CrawArxiv
      run: curl https://arxiv.org/list/cs.CL/recent > ./arxiv.html
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Query
      run: python query.py
      env:
          DATE: ${{env.REPORT_DATE}}
    - name: SendMail
      run: python send_mail.py
      env:
          USERNAME: ${{ secrets.SENDER_MAIL_USERNAME }}
          PASSWORD: ${{ secrets.SENDER_MAIL_PASSWORD }}
          RECEIVERS: ${{ secrets.RECEIVER_ADDR }}
          DATE: ${{env.REPORT_DATE}}

    
